name: saltstack-ferm-formula
source: https://github.com/bechtoldt/saltstack-ferm-formula
summary: SaltStack Formula to set up and configure ferm, a frontend for ip(6)tables
todo:
  - add instructions how to use formhelper, add information about it in the formula-docs (dependency), show up alternative?
  - 'table/ matrix: os/salt compatibility (dedicated file)'
  - add list of available states
  - add tests
  - write states to configure ferm via pillars instead of files
